### ISSUE TITLE
Groq is great, system role next?

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#105]
The Groq's speed is impressive, the responses are instant as if all of them were pre-made. But it lacks personality.
While we have `CUSTOM_PROMPT` that addresses this issue, it would be nice to utilize the system role to determine its behavior.
I believe it's more efficient than inputting
`[user message] (act like Soldier from the 2007 hit game Team Fortress 2. Soldier talks like blah blah blah... He likes buckets and blah blah blah...)`
every single time.

**Comment by dborodin836** [comment]
Hi, @teufortressIndustries.

So, I'm currently working on revamping how we handle command settings because the current setup is a total mess. Everything's stored in this `config.ini` file, and it's getting out of control fast. I'm trying to come up with a better way to manage all this, making it super customizable for each command and allowing user to create as many commands as he wants. I've got a YAML sample of what I'm thinking:

```yaml
commands:
  - name: '!solly'
    type: quick-query
    provider: open-ai
    model: gpt-3.5-turbo-1106
    model_settings:
      max_tokens: 60
    chat_settings:
      # This should resolve the issue. 
      # It stores the soldier's (prompts/soldier.txt) prompt in the system's role message.
      prompt-file: soldier
      message-suffix: 'End your response with "I love buckets btw."'
      enable-soft-limit: false
      allow-prompt-overwrite: false
      allow-long: false
    traits:
      - admin-only
      - openai-moderated
      - empty-prompt-message-response:
          - "Hello there! I'm ChatGPT, integrated into Team Fortress 2. Ask me anything!"
```
There are some things that need to be considered to deem this feature complete. I haven't decided what to do with chats because there is 1 global chat and 1 private chat for each user. 

Anyway, if you want to experiment with it, the available traits and settings are in the `modules.builder` module.
