### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#115]
I just bought a new pc yesterday and decided to try out the v2, but apparently none of the commands work?
I tried removing `- disabled` trait from the commands.yaml but it feels like it did nothing.
![image](https://github.com/user-attachments/assets/7717e221-0f3a-41a6-b890-749adcee1cd0)
![image](https://github.com/user-attachments/assets/9f699a0b-0dfa-472b-8adc-82ada88d3fc4)

**Comment by teufortressIndustries** [comment]
I think i configured everything right?
`-novid -rpt -usercon +ip 0.0.0.0 +rcon_password password +hostport 42465 +con_timestamp 1 +net_start`
config.ini
```
[GENERAL]
TF2_LOGFILE_PATH=C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\console.log
OPENAI_API_KEY=sk-1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL

[GROQ]
GROQ_API_KEY=pipes -> |||||||||||||||

[COMMANDS]
CLEAR_CHAT_COMMAND=!clear
RTD_COMMAND=!rtd

[RCON]
RCON_HOST=127.0.0.1
RCON_PASSWORD=password
RCON_PORT=42465

[CHAT]
; Type: bool [True/False]
;
; Before (ENABLE_SHORTENED_USERNAMES_RESPONSE=True):
; [username] <response goes here>
; After (ENABLE_SHORTENED_USERNAMES_RESPONSE=False):
; <response goes here>
;
; Default = True
ENABLE_SHORTENED_USERNAMES_RESPONSE=True

; MUST include $username
; Type: string
;
; Before (SHORTENED_USERNAMES_FORMAT="[$username] "):
; [username] <response goes here>
; After (SHORTENED_USERNAMES_FORMAT="Response for $username: "):
; Response for username: <response goes here>
;
; Default = "[$username] "
SHORTENED_USERNAMES_FORMAT="[$username] "

; Type: integer
;
; Before (SHORTENED_USERNAME_LENGTH=12):
; [longusername] <response goes here>
; After (SHORTENED_USERNAME_LENGTH=6):
; [longus..] <response goes here>
;
; Default = 12
SHORTENED_USERNAME_LENGTH=12

; Time in seconds
; Type: float
;
; Default: 1.3
DELAY_BETWEEN_MESSAGES=1.3

[MISC]
; Type: bool [True/False]
; Disable the default binding for key presses
; F11 - Start/Stop program
; F10 - Stats command dump
;
; Default = False
DISABLE_KEYBOARD_BINDINGS=False

[STATS]
STEAM_WEBAPI_KEY=Free Items Exploit 2024!!!
ENABLE_STATS_LOGS=False

[CUSTOM-MODEL-GENERAL]
; 127.0.0.1:5000 or your-uri-here.trycloudflare.com
CUSTOM_MODEL_HOST=127.0.0.1:5000

[PERMISSIONS]
; Set to True if the function should fall back to checking the username for admin privileges when the user's SteamID3
; does not match the host's SteamID3.
FALLBACK_TO_USERNAME=True

[EXPERIMENTAL]
; Unlike the standard 'Fire-and-Forget' queue which sends messages without acknowledging
; their delivery, the confirmable queue adds reliability by ensuring that each message is
; successfully delivered. It also integrates additional checks to ascertain if a user
; has been muted by the game, preventing unnecessary message transmission while muted.
; It is considered experimental and may be more error-prone than the standard approach.
; Use with caution, as it may introduce unexpected behavior or performance issues.
; Type: bool [True/False]
;
; Default = False
CONFIRMABLE_QUEUE=False

[FUN]
; 0 - disabled, 1 - rickroll, 2 - random youtube meme
RTD_MODE = 0
```
commands.yaml
```
commands:
  # OpenAI commands
  - name: gpt3
    prefix: '!'
    provider: open-ai
    type: quick-query
    model: gpt-3.5-turbo-1106
    traits:
      - openai-moderated
      - empty-prompt-message-response:
          msg: "Hello there! I am ChatGPT, a ChatGPT plugin integrated into Team Fortress 2. Ask me anything!"

  - name: gpt4
    prefix: '!'
    provider: open-ai
    type: quick-query
    model: gpt-4o
    traits:
      - admin-only
      - openai-moderated

  - name: cgpt
    prefix: '!'
    type: command-global
    provider: open-ai
    model: gpt-3.5-turbo-1106
    traits:
      - openai-moderated

  - name: pc
    prefix: '!'
    type: command-private
    provider: open-ai
    model: gpt-3.5-turbo-1106
    traits:
      - openai-moderated

  # Text-generation-webui commands
  - name: ai
    prefix: '!'
    type: quick-query
    provider: text-generation-webui
    traits:
      

  - name: chat
    prefix: '!'
    type: command-global
    provider: text-generation-webui
    traits:
      

  - name: pcc
    prefix: '!'
    type: command-private
    provider: text-generation-webui
    traits:
      

  # GroqCloud commands
  - name: g
    prefix: '!'
    type: quick-query
    provider: groq-cloud
    model: llama3-70b-8192
    traits:
      

  - name: gc
    prefix: '!'
    type: command-global
    provider: groq-cloud
    model: llama3-70b-8192
    traits:
      

  - name: gpc
    prefix: '!'
    type: command-private
    provider: groq-cloud
    model: llama3-70b-8192
    traits:
      
```
